version: '3'
services:
  dev_container:
    image: dev_container
    container_name: dev_container
    command: 'sleep infinity'
    build: .
    volumes:
      - type: bind
        source: .
        target: /home/user/project
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    
